### ISSUE TITLE
Button position conflict with Level Info in Pause Menu

### ISSUE THREAD

**Issue by Kevadroz** [EKVgd/hidePauseMenuHack#2]
![Screenshot_20240209_145103](https://github.com/EKVgd/hidePauseMenuHack/assets/16049149/31413b7e-c813-43f0-813a-e4434cc03172)
I suggest adding settings for the button placement.

**Comment by Ungeil** [comment]
Done will issue the update on the geode indexer
update can be downloaded from the repo: https://github.com/EKVgd/hidePauseMenuHack/releases/download/v1.1.0/ekv.hidePauseMenuHack.geode
